# Generated by Django 2.0.3 on 2018-04-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_tags'),
        ('Blog', '0004_auto_20180410_1220'),
    ]

    operations = [
    ]
