# Generated by Django 2.0.3 on 2018-04-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_profile'),
        ('Blog', '0005_merge_20180412_1043'),
    ]

    operations = [
    ]
