# Generated by Django 2.0.3 on 2018-04-13 12:50

from django.db import migrations, models
from django.utils.text import slugify


def set_slugs_for_all_blogposts(apps, schema_editor):
    title_list = []
    Post = apps.get_model('Blog', 'Post')
    for post in Post.objects.all():
        post.slug = slugify(post.title)
        if post.title in title_list:
            occurences = title_list.count(post.title)
            post.slug += "-" + str((int(occurences) + 1))
        title_list.append(post.title)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_merge_20180412_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.RunPython(set_slugs_for_all_blogposts),
    ]
