# Generated by Django 2.0.3 on 2018-05-28 07:28

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20180413_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
